name: Build and Release Raylib Project

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build build-essential libgl1-mesa-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev

    - name: Configure CMake
      run: |
        cmake -B build -G Ninja

    - name: Build project
      run: |
        cmake --build build

    - name: Package the build
      run: |
        mkdir release
        cp build/untitled release/
        zip -j untitled-linux.zip release/untitled

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: untitled-linux
        path: untitled-linux.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create or Update Draft Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: nightly-build
        release_name: Nightly Build
        draft: true
        prerelease: true

    - name: Upload ZIP to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: untitled-linux.zip
        asset_name: untitled-linux.zip
        asset_content_type: application/zip
